# Generated by Django 5.2.8 on 2025-11-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="user_likes",
            new_name="user_like",
        ),
    ]
