# Generated by Django 5.2.8 on 2025-11-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_rename_user_likes_image_user_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
