# Generated by Django 5.2.8 on 2025-11-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_image_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="user_like",
            new_name="users_like",
        ),
    ]
